# Generated by Django 6.0.4 on 2026-05-02 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
