# Generated by Django 6.0.4 on 2026-05-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_backend', '0002_remove_order_customer_delete_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
