# Generated by Django 6.0.4 on 2026-05-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos_backend', '0003_alter_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
